apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s
  template:
    metadata:
      labels:
        app: k8s
    spec:
      containers:
        - name: k8s
          image: k8s
          imagePullPolicy: Never
          ports:
            - containerPort: 8080