apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: k8s
    context: .
    jib: {}
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - dp.yaml       
portForward:
- resourceType: deployment
  resourceName: k8s
  namespace: test  # 
  port: 8080 # 
  localPort: 8080
      
